workspace:
  base: /go
  path: src/github.com/kowala-tech/kcoin

clone:
  git:
    image: plugins/git:next
    pull: true
    tags: true

pipeline:
  install_tools:
    group: setup
    image: kowalatech/go:1.0.12
    commands:
      - env
      - command -v mockery
      - mockery
      - make install_tools
    when:
      event: [pull_request]
