workspace:
  base: /go
  path: src/github.com/kowala-tech/kcoin

clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  test:
    group: testing
    image: kowalatech/go:1.0.3
    commands:
      - make test
      - make lint
    when:
      event: [pull_request]

  docker_kusd_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: kcoin.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_bootnode_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: bootnode.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_faucet_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: faucet.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_kusd_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: kcoin.Dockerfile
    when:
      event: tag

  docker_bootnode_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: bootnode.Dockerfile
    when:
      event: tag

  docker_faucet_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: faucet.Dockerfile
    when:
      event: tag

  build-artifacts:
    image: kowalatech/go:1.0.3
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - make kcoin-cross
    when:
      event: [push, tag]
      branch: [dev]

  s3:
    image: plugins/s3
    bucket: releases.kowala.io
    region: us-east-1
    acl: public-read
    source: build/bin/kcoin-*.zip
    strip_prefix: build/bin/
    target: /
    secrets: [aws_access_key_id, aws_secret_access_key]
    when:
      event: [push, tag]
      branch: [dev]

  notify-dev:
    group: notify
    image: plugins/slack
    secrets: [ slack_webhook ] 
    channel: ci-notifications
    username: drone
    template: >
        *CI build #{{build.number}}* ({{build.event}} to `{{build.branch}}`{{#if build.pull}}[PR #{{build.pull}}]{{/if}} by @{{build.author}}) *{{#success build.status}}successful{{else}}failed{{/success}}* after {{since build.started}}

        _${DRONE_COMMIT_MESSAGE}_
        
        {{#if build.tag}}`v{{build.tag}}` | {{/if}}Commit <${DRONE_COMMIT_LINK}|{{build.commit}}> | <{{build.link}}|Build #{{build.number}}>
    when:
      status: failure 
      event: [push, tag, pull_request]

services:
  docker:
    image: docker:dind
    command: [ '-l', 'fatal' ]
    privileged: true
