workspace:
  base: /go
  path: src/github.com/kowala-tech/kcoin

clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  test:
    image: kowalatech/go:1.0.1
    commands:
      - make test
      - make lint
    when:
      event: [pull_request]

  build:
    image: kowalatech/go:1.0.1
    commands:
      - make
    when:
      event: [push, tag]
      branch: [master, dev, refs/tags/*]

  doc-build-dev:
    image: kowalatech/kman
    commands:
      - mkdir -p docs/public
      - kman --theme /kowala/kowala.tech/themes/kman --output docs/public
    when:
      event: [push, tag]
      branch: [master, dev, feature/*]

  doc-deploy-dev:
    group: deploy
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "dev-docs.kowala.io"
    source: docs/public/**/*
    strip_prefix: docs/public
    target: /
    encryption: AES256
    when:
      event: [push]
      branch: [dev, feature/end-user-docs]

  docker_kusd_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: kcoin.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_bootnode_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: bootnode.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_faucet_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: faucet.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_kusd_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: kcoin.Dockerfile
    when:
      event: tag

  docker_bootnode_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: bootnode.Dockerfile
    when:
      event: tag

  docker_faucet_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: faucet.Dockerfile
    when:
      event: tag
