workspace:
  base: /go
  path: src/github.com/kowala-tech/kcoin

clone:
  git:
    image: plugins/git:next
    pull: true
    tags: true

pipeline:
  go-generate:
    image: kowalatech/go:1.0.11
    commands:
    - make go_generate
    - make assert_no_changes
    when:
      event: [push]

  test_kcoin:
    group: testing
    image: kowalatech/go:1.0.11
    commands:
      # test_genesis should run before test
      - make test_genesis
      - make test
      - make lint
    secrets: [ slack_app_webhook ]
    when:
      event: [pull_request]

  test_notifications:
    group: testing
    image: kowalatech/go:1.0.11
    environment:
      - NSQ_ADDR=nsqd:4150
      - REDIS_ADDR=redis:6379
    commands:
      - make test_notifications
    when:
      event: [pull_request]

  test_truffle:
    group: testing
    image: node:9
    commands:
      - make test_truffle
    when:
      event: [pull_request]

  e2e:
    group: testing
    image: kowalatech/go:1.0.11
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_PUBLIC_IP=docker
    commands:
      - make -j 4 dev_docker_images
      - make e2e
    when:
      event: [pull_request]

  wallet_app:
    group: testing
    image: node:9
    commands:
      - make wallet_app_tests
    when:
      event: [pull_request]

  docker_build:
    image: kowalatech/go:1.0.11
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_PUBLIC_IP=docker
    commands:
      - make -j 4 dev_docker_images
    when:
      event: [push]

  docker_kusd:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kusd
    dockerfile: client/release/kcoin.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_bootnode:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/bootnode
    dockerfile: client/release/bootnode.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_faucet:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/faucet
    dockerfile: client/release/faucet.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_notifications_api:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/backend_api
    dockerfile: notifications/api.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_notifications_emailer:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/emailer
    dockerfile: notifications/emailer.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_notifications_db_sync:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/transactions_persistance
    dockerfile: notifications/transactions_db_synchronize.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_netstats:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/netstats
    dockerfile: netstats/Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_explorer_web:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kexplorer
    dockerfile: explorer/web.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_explorer_sync:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kexplorersync
    dockerfile: explorer/sync.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  docker_notifications_tx_publisher:
    group: docker_deployment
    image: kowalatech/drone-docker
    repo: kowalatech/transactions_publisher
    dockerfile: notifications/transactions_publisher.Dockerfile
    pull: true
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    when:
      branch: [dev, master]
      event: [push, tag]

  build_artifacts:
    group: build_artifacts
    image: kowalatech/go:1.0.11
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - make kcoin_cross
    when:
      event: [push, tag]
      branch: [dev]

  compile_gource_video:
    group: build_artifacts
    image: adk486/docker-gource
    repo: kowalatech/kcoin
    when:
      branch: [dev]
      event: [push]

  build_docs:
    group: build_artifacts
    image: kowalatech/mkdocs
    commands:
      - make build_docs
    when:
      event: [push,tag]
      branch: [master,dev]

  build_wallet_app:
    group: build_artifacts
    image: node:9
    environment:
      - KOWALA_NETWORK="kusd-zygote"
    commands:
      - cd wallet-app ; yarn run drone:build
    when:
      event: [push]
      branch: [master]

  upload_gource_mp4_to_s3:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: public-read
    encryption: AES256
    bucket: releases.kowala.io
    source: gource-audio.mp4
    target: /kowala-kcoin-development-history.mp4
    when:
      branch: [dev]
      event: [push]

  upload_binary_assets_to_s3:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: public-read
    encryption: AES256
    bucket: releases.kowala.io
    source: client/build/bin/kcoin-*.zip
    strip_prefix: client/build/bin/
    target: /
    when:
      event: [push, tag]
      branch: [dev]

  upload_kusd_zygote:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: public-read
    encryption: AES256
    bucket: "wallet.zygote.kowala.io"
    source: dist/**/*
    strip_prefix: dist
    target: /
    when:
      event: [push]
      branch: [master]

  upload_dev_docs_to_s3:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: public-read
    encryption: AES256
    bucket: "docs.kowala.io"
    source: docs/site/**/*
    strip_prefix: docs/site
    target: /
    when:
      event: [push]
      branch: [dev]

  upload_prod_docs_to_s3:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: public-read
    encryption: AES256
    bucket: "docs.kowala.tech"
    source: docs/site/**/*
    strip_prefix: docs/site
    target: /
    when:
      event: [push,tag]
      branch: [master]

  upload_e2e_logs:
    group: asset_deployment
    image: plugins/s3
    region: us-east-1
    acl: private
    encryption: AES256
    bucket: "kcoin-e2e"
    source: e2e/logs/*
    strip_prefix: e2e/logs
    target: /logs/${DRONE_BUILD_NUMBER}
    when:
      status: failure
      event: [pull_request]

  notify_dev:
    group: notify
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci-notifications
    username: drone
    template: >
        *CI build #{{build.number}}* ({{build.event}} to `{{build.branch}}`{{#if build.pull}}[PR #{{build.pull}}]{{/if}} by @{{build.author}}) *{{#success build.status}}successful{{else}}failed{{/success}}* after {{since build.started}}

        _${DRONE_COMMIT_MESSAGE}_

        {{#if build.tag}}`v{{build.tag}}` | {{/if}}Commit <${DRONE_COMMIT_LINK}|{{build.commit}}> | <{{build.link}}|Build #{{build.number}}>
    when:
      status: failure
      event: [push, tag, pull_request]

services:
  docker:
    image: docker:dind
    command: [ '-l', 'fatal' ]
    privileged: true

  nsqlookupd:
    image: nsqio/nsq
    commands:
      - /nsqlookupd

  nsqd:
    image: nsqio/nsq
    commands:
      - /nsqd --lookupd-tcp-address=nsqlookupd:4160

  redis:
    image: redis:alpine
