workspace:
  base: /go
  path: src/github.com/kowala-tech/kcoin

clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  test:
    group: testing
    image: kowalatech/go:1.0.3
    commands:
      - make test
      - make lint
    when:
      event: [pull_request]

  e2e:
    group: testing
    image: kowalatech/go:1.0.3
    commands:
      - make e2e
    secrets: [ k8s_docker_host, k8s_cluster_ip, k8s_cluster_master_url, k8s_cluster_token]
    when:
      event: [pull_request]
    volumes:
      - /home/ubuntu/.minikube:/root/.minikube:ro
      - /home/ubuntu/.kube:/root/.kube:ro

  build:
    image: kowalatech/go:1.0.3
    commands:
      - make
    when:
      event: [push, tag]
      branch: [master, dev, refs/tags/*]

  docker_kusd_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: kcoin.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_bootnode_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: bootnode.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_faucet_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    tags: dev
    dockerfile: faucet.Dockerfile
    when:
      branch: [dev]
      event: [push, tag]

  docker_kusd_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/kusd
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: kcoin.Dockerfile
    when:
      event: tag

  docker_bootnode_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/bootnode
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: bootnode.Dockerfile
    when:
      event: tag

  docker_faucet_tag:
    group: docker-deployment
    image: kowalatech/drone-docker
    repo: kowalatech/faucet
    secrets: [ docker_username, docker_password ]
    privileged: true
    auto_tag: true
    dockerfile: faucet.Dockerfile
    when:
      event: tag
