version: '2'

services:
  backend:
    build:
      context: ..
      dockerfile: ./wallet-backend/Dockerfile
    ports:
    - "8080:8080"
    environment:
    - NODE_ENDPOINT=http://rpcnode.zygote.kowala.tech:30503
    - TX_MS_ENDPOINT=api:3000
    networks:
      - notifications_default

networks:
  notifications_default:
    external: true
